// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAJY7fDXQb-IACNDcY5MrDrZWCfQEPEoQ',
    appId: '1:487784821820:web:ca584cdda02f5fef487f39',
    messagingSenderId: '487784821820',
    projectId: 'first-app-4d9b7',
    authDomain: 'first-app-4d9b7.firebaseapp.com',
    storageBucket: 'first-app-4d9b7.appspot.com',
    measurementId: 'G-JSBYL4BDRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA3xQwRBTy0whjRrCWfwhSUulEvKtIazw',
    appId: '1:487784821820:android:dc2768f5c57645a0487f39',
    messagingSenderId: '487784821820',
    projectId: 'first-app-4d9b7',
    storageBucket: 'first-app-4d9b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVmm3ZEwicIQ-8WEDvDZlRdP3O0CM7Ccc',
    appId: '1:487784821820:ios:b8cc8203bd4c2259487f39',
    messagingSenderId: '487784821820',
    projectId: 'first-app-4d9b7',
    storageBucket: 'first-app-4d9b7.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVmm3ZEwicIQ-8WEDvDZlRdP3O0CM7Ccc',
    appId: '1:487784821820:ios:b8cc8203bd4c2259487f39',
    messagingSenderId: '487784821820',
    projectId: 'first-app-4d9b7',
    storageBucket: 'first-app-4d9b7.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAJY7fDXQb-IACNDcY5MrDrZWCfQEPEoQ',
    appId: '1:487784821820:web:d188674a5dbf5f9b487f39',
    messagingSenderId: '487784821820',
    projectId: 'first-app-4d9b7',
    authDomain: 'first-app-4d9b7.firebaseapp.com',
    storageBucket: 'first-app-4d9b7.appspot.com',
    measurementId: 'G-XKB25DT7TM',
  );
}
